# Generated by Django 5.2.4 on 2025-07-16 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askuenr', '0002_contactinfo_event_scholarship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='chancellor',
            field=models.OneToOneField(blank=True, help_text='The current Chancellor of the University.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chancellor_of_university', to='askuenr.staffprofile'),
        ),
    ]
