# Generated by Django 5.2.4 on 2025-07-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askuenr', '0004_university_dean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(choices=[('C', 'Chancellor'), ('VC', 'Vice-Chancellor'), ('Pro-VC', 'Pro Vice-Chancellor'), ('Registrar', 'Registrar'), ('Lecturer', 'Lecturer'), ('Snr. Lecturer', 'Senior Lecturer'), ('Assoc. Prof.', 'Associate Professor'), ('Admin Staff', 'Administrative Staff'), ('Other', 'Other Staff')], max_length=100),
        ),
    ]
