# Generated by Django 5.2.4 on 2025-07-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askuenr', '0005_alter_staffprofile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpa',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='academicrecord',
            options={'ordering': ['academic_year', 'semester', 'course'], 'verbose_name_plural': 'Academic Records'},
        ),
        migrations.AlterUniqueTogether(
            name='academicrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gpa',
            name='score',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='academicrecord',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
