# Generated by Django 5.2.4 on 2025-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askuenr', '0006_remove_gpa_student_alter_academicrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpa',
            options={'ordering': ['-upper_bound'], 'verbose_name_plural': 'GPAs'},
        ),
        migrations.RemoveField(
            model_name='gpa',
            name='gpa_value',
        ),
        migrations.RemoveField(
            model_name='gpa',
            name='score',
        ),
        migrations.AddField(
            model_name='gpa',
            name='grade_point',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grade point equivalent, e.g. 4.00', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='gpa',
            name='interpretation',
            field=models.CharField(blank=True, help_text='Interpretation of the grade, e.g. Excellent, Good', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gpa',
            name='letter_grade',
            field=models.CharField(blank=True, help_text='Letter grade, e.g. A, B+, C+', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='gpa',
            name='lower_bound',
            field=models.IntegerField(blank=True, help_text='Lower bound of the score range (inclusive), e.g. 80', null=True),
        ),
        migrations.AddField(
            model_name='gpa',
            name='upper_bound',
            field=models.IntegerField(blank=True, help_text='Upper bound of the score range (inclusive), e.g. 100', null=True),
        ),
    ]
