# Generated by Django 5.2.4 on 2025-07-16 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askuenr', '0008_alter_staffprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='gpa',
            field=models.ForeignKey(blank=True, help_text='Linked GPA record based on the raw score.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='askuenr.gpa'),
        ),
    ]
