# Generated by Django 5.2.4 on 2025-09-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askuenr', '0009_academicrecord_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(choices=[('C', 'Chancellor'), ('VC', 'Vice-Chancellor'), ('Pro-VC', 'Pro Vice-Chancellor'), ('Registrar', 'Registrar'), ('Lecturer', 'Lecturer'), ('Src', 'Src'), ('Snr. Lecturer', 'Senior Lecturer'), ('HOD. Prof.', 'Head Of Department IT'), ('Admin Staff', 'Administrative Staff'), ('Other', 'Other Staff')], max_length=100),
        ),
    ]
