# Generated by Django 5.2.4 on 2025-09-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askuenr', '0011_alter_staffprofile_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('source', models.CharField(choices=[('JSON', 'JSON'), ('Gemini', 'Gemini'), ('Fallback', 'Fallback')], default='JSON', max_length=50)),
                ('is_ai_augmented', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
